# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target '知识大综合_Demo' do

pod ‘AFNetworking’
pod ‘MBProgressHUD’
pod ‘Diplomat’
end

target '知识大综合_DemoTests' do

end

target '知识大综合_DemoUITests' do

end

